//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class TrainingSet
{

    private TrainingSetPlatoon[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Platoon", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TrainingSetPlatoon[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TrainingSetPlatoon
{

    private TrainingSetPlatoonSquad[] squadField;

    private string totalPlayersField;

    private string minimumSizeField;

    private string playersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Squad", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TrainingSetPlatoonSquad[] Squad
    {
        get
        {
            return this.squadField;
        }
        set
        {
            this.squadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string totalPlayers
    {
        get
        {
            return this.totalPlayersField;
        }
        set
        {
            this.totalPlayersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minimumSize
    {
        get
        {
            return this.minimumSizeField;
        }
        set
        {
            this.minimumSizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string players
    {
        get
        {
            return this.playersField;
        }
        set
        {
            this.playersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TrainingSetPlatoonSquad
{

    private TrainingSetPlatoonSquadFireteam[] fireteamField;

    private string playersField;

    private string minimumSizeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Fireteam", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TrainingSetPlatoonSquadFireteam[] Fireteam
    {
        get
        {
            return this.fireteamField;
        }
        set
        {
            this.fireteamField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string players
    {
        get
        {
            return this.playersField;
        }
        set
        {
            this.playersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minimumSize
    {
        get
        {
            return this.minimumSizeField;
        }
        set
        {
            this.minimumSizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TrainingSetPlatoonSquadFireteam
{

    private string playersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string players
    {
        get
        {
            return this.playersField;
        }
        set
        {
            this.playersField = value;
        }
    }
}
